spring.application.name=api
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

logging.level.root=error
logging.level.org.michel=info
loggin.level.org.springframeword.boot.autoconfigure.h2=INFO
loggin.level.org.springframeword.boot.web.embedded.tomcat=INFO




